{"identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/errorData(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"Case","externalID":"s:9AsyncMoya9DataErrorO05errorC0yACSScACmF","symbolKind":"case","modules":[{"name":"AsyncMoya"}],"title":"DataError.errorData(_:)","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"abstract":[{"text":"서버로부터 받은 오류 메시지 문자열을 직접 저장할 때 사용합니다.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"variants":[{"paths":["\/documentation\/asyncmoya\/dataerror\/errordata(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://AsyncMoya/documentation/AsyncMoya":{"url":"\/documentation\/asyncmoya","role":"collection","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"title":"AsyncMoya","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/errorData(_:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/errorData(_:)","title":"DataError.errorData(_:)","role":"symbol","abstract":[{"text":"서버로부터 받은 오류 메시지 문자열을 직접 저장할 때 사용합니다.","type":"text"}],"url":"\/documentation\/asyncmoya\/dataerror\/errordata(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataError"}],"navigatorTitle":[{"kind":"identifier","text":"DataError"}],"type":"topic","title":"DataError","url":"\/documentation\/asyncmoya\/dataerror","role":"symbol","abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"}}}