{"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"platforms":["macOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError"},"metadata":{"title":"DataError.unknownError","modules":[{"name":"AsyncMoya"}],"role":"symbol","symbolKind":"case","externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}],"roleHeading":"Case"},"variants":[{"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"type":"topic","title":"AsyncMoya","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","url":"\/documentation\/asyncmoya","abstract":[{"text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리","type":"text"}],"role":"collection","kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"title":"DataError.unknownError","type":"topic","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","abstract":[{"type":"text","text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다."}],"url":"\/documentation\/asyncmoya\/dataerror\/unknownerror","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"type":"topic","title":"DataError","kind":"symbol","url":"\/documentation\/asyncmoya\/dataerror","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}]}}}