{"abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)"},"metadata":{"externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF","roleHeading":"Case","role":"symbol","modules":[{"name":"AsyncMoya"}],"title":"DataError.customError(_:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError"},{"kind":"text","text":")"}],"symbolKind":"case"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["macOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"url":"\/documentation\/asyncmoya\/responseerror","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResponseError","kind":"identifier"}],"navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"title":"ResponseError","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","abstract":[{"type":"text","text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다."}],"role":"symbol","kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","url":"\/documentation\/asyncmoya","title":"AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"role":"collection","type":"topic","kind":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"type":"topic","abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","title":"DataError.customError(_:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"type":"topic","title":"DataError","kind":"symbol","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","url":"\/documentation\/asyncmoya\/dataerror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataError"}],"abstract":[{"text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataError"}]}}}