{"variants":[{"paths":["\/documentation\/asyncmoya\/dataerror\/customerror(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다."}],"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"customError","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"DataError.customError(_:)","modules":[{"name":"AsyncMoya"}],"role":"symbol","externalID":"s:9AsyncMoya9DataErrorO06customD0yAcA08ResponseD0VcACmF"},"references":{"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"url":"\/documentation\/asyncmoya\/dataerror","type":"topic","kind":"symbol","title":"DataError","role":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/customError(_:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"customError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:9AsyncMoya13ResponseErrorV","text":"ResponseError"},{"kind":"text","text":")"}],"kind":"symbol","title":"DataError.customError(_:)","abstract":[{"text":"서버에서 반환한 커스텀 에러 응답을 래핑합니다.","type":"text"}],"role":"symbol","type":"topic","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/customError(_:)","url":"\/documentation\/asyncmoya\/dataerror\/customerror(_:)"},"doc://AsyncMoya/documentation/AsyncMoya/ResponseError":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ResponseError"}],"url":"\/documentation\/asyncmoya\/responseerror","kind":"symbol","type":"topic","navigatorTitle":[{"text":"ResponseError","kind":"identifier"}],"abstract":[{"text":"서버로부터 반환된 에러 응답을 표현하는 모델입니다.","type":"text"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/ResponseError","title":"ResponseError","role":"symbol"},"doc://AsyncMoya/documentation/AsyncMoya":{"url":"\/documentation\/asyncmoya","type":"topic","title":"AsyncMoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya","kind":"symbol","role":"collection"}}}