{"sections":[],"identifier":{"url":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/AsyncMoya\/documentation\/AsyncMoya","doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError"]]},"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Case","title":"DataError.unknownError","symbolKind":"case","externalID":"s:9AsyncMoya9DataErrorO07unknownD0yA2CmF","modules":[{"name":"AsyncMoya"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unknownError","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/asyncmoya\/dataerror\/unknownerror"]}],"references":{"doc://AsyncMoya/documentation/AsyncMoya":{"title":"AsyncMoya","kind":"symbol","url":"\/documentation\/asyncmoya","abstract":[{"type":"text","text":"Moya를 위한 현대적인 async\/await, Combine, RxSwift 확장 라이브러리"}],"type":"topic","role":"collection","identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya"},"doc://AsyncMoya/documentation/AsyncMoya/DataError/unknownError":{"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError\/unknownError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknownError"}],"kind":"symbol","url":"\/documentation\/asyncmoya\/dataerror\/unknownerror","role":"symbol","abstract":[{"type":"text","text":"그 외 알 수 없는 오류 상황을 처리할 때 사용합니다."}],"title":"DataError.unknownError","type":"topic"},"doc://AsyncMoya/documentation/AsyncMoya/DataError":{"title":"DataError","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DataError","kind":"identifier"}],"url":"\/documentation\/asyncmoya\/dataerror","kind":"symbol","abstract":[{"type":"text","text":"네트워크 요청 및 응답 처리 중 발생할 수 있는 다양한 오류를 표현하는 열거형"}],"navigatorTitle":[{"text":"DataError","kind":"identifier"}],"identifier":"doc:\/\/AsyncMoya\/documentation\/AsyncMoya\/DataError","role":"symbol"}}}